# compile:
#
#   make -C /lib/modules/`uname -r`/build M=`pwd` modules
#   make -C /lib/modules/`uname -r`/build M=`pwd` clean
#
#   CONFIG_MYDEMO=m make -C /lib/modules/`uname -r`/build M=`pwd` modules

# mydemo-y += a.o b.o
# obj-$(CONFIG_MYDEMO) += mydemo.o

# obj-$(CONFIG_MYDEMO) = mydemo.o

obj-y = mydemo.o
