all : preadb pwriteb preadl pwritel

preadb: preadb.c
	gcc -g preadb.c -o preadb

pwriteb: pwriteb.c
	gcc -g pwriteb.c -o pwriteb

preadl: preadl.c
	gcc -g preadl.c -o preadl

pwritel: pwritel.c
	gcc -g pwritel.c -o pwritel

clean:
	rm -f preadb pwriteb preadl pwritel
